name: opsops
version: 0.0.1
github: vst/opsops
license: MIT
author: Vehbi Sinan Tunalioglu
maintainer: vst@vsthost.com
copyright: Copyright (c) 2024 Vehbi Sinan Tunalioglu
extra-source-files:
  - README.md
  - CHANGELOG.md
description: Please see the README on GitHub at <https://github.com/vst/opsops#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  ghc-options:
    - '-Wall'
    - '-Werror'
    - '-Wunused-packages'
  dependencies:
    - aeson
    - bytestring
    - containers
    - exceptions
    - optparse-applicative
    - path
    - path-io
    - string-interpolate
    - text
    - typed-process
    - yaml
executables:
  opsops:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - opsops
tests:
  opsops-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies: []
  opsops-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-threaded'
    dependencies:
      - opsops
      - doctest
