name: "Check, Test and Build Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v17"

      - name: "Check, Test and Build"
        run: |
          nix develop --command bash -c "cabal update --ignore-project && cabal dev-test-build"

      - name: "Build Docker Image"
        run: |
          nix build .#docker

      - name: "Load Docker Image"
        run: |
          docker load <./result
