name: "Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  release-please:
    runs-on: "ubuntu-latest"

    steps:
      - id: "release"
        name: "Release"
        uses: "googleapis/release-please-action@v4"

      - name: "Checkout Codebase"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "DeterminateSystems/nix-installer-action@v17"

      - name: "Build Statically Compiled Executable"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          nix develop --command bash build-static.sh

      - name: "Upload Release Artifact"
        if: "${{ steps.release.outputs.release_created }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release upload "${{ steps.release.outputs.tag_name }}" /tmp/opsops-static-linux-x86_64
